steps:
  - task: NodeTool@0
    displayName: Install Node.JS
    inputs:
      versionSpec: '12.x'

  - script: |
      yarn install --frozen-lockfile --ignore-optional --ignore-platform
    displayName: yarn install
